### ISSUE TITLE
[BUG] Study model의 leader는 OneToOneField vs ForeignKey?

### ISSUE THREAD

**Issue by lijm1358** [PNU-AID/AID_Backend_v2#28]
### 버그 설명

Study 모델의 leader가 OneToOneField로 되어있는데, 의도된 relation인가요(사용자는 하나의 스터디만 열 수 있음)? notion의 ERD는 1:N관계로 보입니다(사용자는 여러개의 스터디를 열 수 있음).

### 재현 방법

현재 push된 branch로부터 재현은 불가능.
django에 authentication이 가능하게 한 뒤, leader에 로그인한 사용자를 지정하여 study object를 만든 뒤 다시 만들게 되면 발생.

### 예상 동작

스터디 생성을 중복 요청해도 오류 발생 X. 한 사용자가 여러 개의 스터디를 만들 수 없는 것이 의도된 것이라면 현재 동작이 정상적인 것.

### 스크린샷

* 동일한 User가 스터디를 2개 이상 생성하려고 할 때 오류 발생
![image](https://github.com/PNU-AID/AID_Backend_v2/assets/24501646/7947dbbb-97e5-4b63-9eae-a41e997c51dd)

### 추가 정보

https://velog.io/@mquat/django-onetoonefield-foreinkey

**Comment by lijm1358** [comment]
@sihyeong671 @June222

**Comment by June222** [comment]
의미적인 차이인데, leader를 스터디를 여는 사람이 아닌 팀장으로 생각하고 정한 것이라 의도된 것은 맞습니다.

동일한 유저가 두 개의 스터디 팀장을 맡는 것에 대해서는 어떻게 생각하시나요? @lijm1358  @sihyeong671  @best11gh

**Comment by June222** [comment]
그리고 ERD는 중간 변동 사항을 반영하지않은 초기 상태에 머물러있습니다.

**Comment by sihyeong671** [comment]
팀장은 여러명이 되어도 괜찮을 것 같습니다

**Comment by lijm1358** [comment]
회의 후 #29 에 의해 ForeignKey로 변경되었습니다
